// <auto-generated />
using System;
using EHRS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EHRS.Infrastructure.Migrations
{
    [DbContext(typeof(EHRSContext))]
    [Migration("20260430133008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForVisit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCC2783685B3");

                    b.HasIndex(new[] { "DoctorId", "AppointmentDateTime" }, "IX_Appointment_DoctorDate")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PatientId", "AppointmentDateTime" }, "IX_Appointment_PatientDate")
                        .IsDescending(false, true);

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("About")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AffiliatedHospital")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Certificates")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MedicalLicense")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("DoctorId")
                        .HasName("PK__Doctor__2DC00EBFD60A7CF8");

                    b.HasIndex(new[] { "Area" }, "IX_Doctor_Area");

                    b.HasIndex(new[] { "Email" }, "UX_Doctor_Email")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Radiology")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("RecordDateTime")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Treatment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecordId")
                        .HasName("PK__MedicalR__FBDF78E942C14556");

                    b.HasIndex(new[] { "DoctorId", "RecordDateTime" }, "IX_MedicalRecord_DoctorDate")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PatientId", "RecordDateTime" }, "IX_MedicalRecord_PatientDate")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "AppointmentId" }, "UX_MedicalRecord_Appointment")
                        .IsUnique();

                    b.ToTable("MedicalRecord", (string)null);
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Diseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short?>("HeightCm")
                        .HasColumnType("smallint");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("000-00-0000")
                        .HasColumnName("SSN");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__970EC36617F9ED89");

                    b.HasIndex(new[] { "Ssn" }, "UQ_Patient_SSN")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UX_Patient_Email")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.SensorDatum", b =>
                {
                    b.Property<long>("SensorDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SensorDataId"));

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("HeartRate")
                        .HasColumnType("smallint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PressureHeart")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("pressure_heart");

                    b.Property<decimal?>("SpO2")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("Timestamp")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("SensorDataId")
                        .HasName("PK__SensorDa__14C8841083793CAD");

                    b.HasIndex(new[] { "PatientId", "Timestamp" }, "IX_SensorData_PatientTime")
                        .IsDescending(false, true);

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.SurgeryHistory", b =>
                {
                    b.Property<int>("SurgeryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurgeryId"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SurgeryDate")
                        .HasColumnType("date");

                    b.Property<string>("SurgeryType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SurgeryId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("SurgeryHistory");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.UserCredential", b =>
                {
                    b.Property<int>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CredentialId")
                        .HasName("PK__UserCred__2C58F9CC9A9B9E42");

                    b.HasIndex(new[] { "DoctorId" }, "UX_UserCredential_DoctorId")
                        .IsUnique()
                        .HasFilter("([DoctorId] IS NOT NULL)");

                    b.HasIndex(new[] { "PatientId" }, "UX_UserCredential_PatientId")
                        .IsUnique()
                        .HasFilter("([PatientId] IS NOT NULL)");

                    b.ToTable("UserCredential", (string)null);
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Appointment", b =>
                {
                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Doctor");

                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.MedicalRecord", b =>
                {
                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("EHRS.Infrastructure.Persistence.Entities.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecord_Appointment");

                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecord_Doctor");

                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecord_Patient");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.SensorDatum", b =>
                {
                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Patient", "Patient")
                        .WithMany("SensorData")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SensorData_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.SurgeryHistory", b =>
                {
                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Doctor", "Doctor")
                        .WithMany("SurgeryHistories")
                        .HasForeignKey("DoctorId");

                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Patient", "Patient")
                        .WithMany("SurgeryHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.UserCredential", b =>
                {
                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Doctor", "Doctor")
                        .WithOne("UserCredential")
                        .HasForeignKey("EHRS.Infrastructure.Persistence.Entities.UserCredential", "DoctorId")
                        .HasConstraintName("FK_UserCredential_Doctor");

                    b.HasOne("EHRS.Infrastructure.Persistence.Entities.Patient", "Patient")
                        .WithOne("UserCredential")
                        .HasForeignKey("EHRS.Infrastructure.Persistence.Entities.UserCredential", "PatientId")
                        .HasConstraintName("FK_UserCredential_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("SurgeryHistories");

                    b.Navigation("UserCredential");
                });

            modelBuilder.Entity("EHRS.Infrastructure.Persistence.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("SensorData");

                    b.Navigation("SurgeryHistories");

                    b.Navigation("UserCredential");
                });
#pragma warning restore 612, 618
        }
    }
}
