apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ehrs-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nasser-tarek/Depi_project'
    targetRevision: HEAD
    path: K3s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: depi   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   