import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Lang = "en" | "ar";

const translations = {
  en: {
    // Sidebar
    healthcarePortal: "Healthcare Portal",
    mainMenu: "Main Menu",
    dashboard: "Dashboard",
    appointments: "Appointments",
    medicalRecords: "Records",
    doctorProfile: "Profile",
    searchPatientNav: "Search",
    surgeriesNav: "Surgeries",

    // Header
    language: "English",
    searchPatients: "Search patients…",

    // Dashboard
    drName: "Dr. John Doe",
    noRecentVisits: "No recent visits recorded.",
    noAppointmentsFound: "No appointments found.",
    noImagingFound: "No imaging records found.",
    bookingSelectAreaFirst: "Please select a governorate first.",
    bookingSelectSpecialtyFirst: "Please select a specialty first.",
    bookingFillAllFields: "Please fill all required fields.",
    bookingSuccess: "Appointment booked successfully!",
    bookingDuplicate: "You already have an appointment on this date.",
    bookingPastDate: "Please select a today or future date.",
    bookingAvailableDoctors: "Available Doctors",
    bookingNoSlots: "No doctors available for this selection.",
    selectGovernorate: "Select Governorate",
    phoneInvalid: "Phone number must be 11 digits.",
    dobInvalid: "Please enter a valid date of birth.",
    imageTypeError: "Only JPEG, PNG, and WebP images are supported.",
    selectBloodType: "Select blood type",
    cardiologist: "Cardiologist",
    todaysAppointments: "Today's Appointments",
    patient: "Patient",
    status: "Status",

    // Appointments
    manageAppointments: "Manage and view all patient appointments",
    upcoming: "Upcoming",
    past: "Past",
    upcomingAppointments: "Upcoming Appointments",
    pastAppointments: "Past Appointments",
    searchPatient: "Search patient...",
    date: "Date",
    type: "Type",
    id: "ID",

    // Statuses
    waiting: "Waiting",
    completed: "Completed",
    cancelled: "Cancelled",
    scheduled: "Scheduled",

    // Medical Records
    generalDocuments: "General Documents / Medical Records",
    patientRecords: "Patient Records",
    searchPatientRecord: "Search patient…",
    diagnosis: "Diagnosis",
    treatment: "Treatment",
    action: "Action",
    view: "View",
    addRecord: "Add Record",

    // New Medical Record
    newMedicalRecord: "New Medical Record",
    fillDetails: "Fill in the details to create a new medical record",
    backToMedicalRecords: "Back to Medical Records",
    referenceIds: "Reference IDs",
    patientId: "Patient ID",
    doctorId: "Doctor ID",
    appointmentId: "Appointment ID",
    searchPatientId: "Search patient ID…",
    searchDoctorId: "Search doctor ID…",
    searchAppointmentId: "Search appointment ID…",
    medicalInformation: "Medical Information",
    chiefComplaint: "Chief Complaint",
    clinicalNotes: "Clinical Notes",
    describeComplaint: "Describe the patient's chief complaint…",
    enterDiagnosis: "Enter diagnosis…",
    addClinicalNotes: "Add clinical notes and observations…",
    describeTreatment: "Describe treatment plan…",
    attachments: "Attachments",
    prescription: "Prescription",
    radiology: "Radiology",
    noFileChosen: "No file chosen",
    chooseFile: "Choose File",
    cancel: "Cancel",

    // Doctor Profile
    editProfile: "Edit Profile",
    saveProfile: "Save Profile",
    medicalLicense: "Medical License",
    contact: "Contact",
    affiliatedHospital: "Affiliated Hospital",
    about: "About",
    cardiology: "Cardiology",

    // Not Found
    notFound: "404",
    pageNotFound: "Oops! Page not found",
    returnHome: "Return to Home",

    // Search Patient Page
    searchPatientPage: "Search Patient",
    medicalHistoryTab: "Medical History",
    surgeryTab: "Surgery",
    enterPatientId: "Enter National ID",
    searchBtn: "Search",
    patientNotFound: "Patient not found. Please check the ID.",
    idTooShort: "The National ID must be exactly 14 digits. You entered fewer digits.",
    idTooLong: "The National ID must be exactly 14 digits. You entered more digits.",
    idInvalid: "The National ID must contain only numbers.",
    bloodType: "Blood Type",
    age: "Age",
    weight: "Weight",
    height: "Height",
    bmi: "BMI",
    years: "years",
    kg: "kg",
    cm: "cm",
    chronicDiseases: "Chronic Diseases",
    allergiesLabel: "Allergies",
    doctor: "Doctor",
    surgicalHistory: "Surgical History",
    operationName: "Operation Name",

    // Surgeries Page
    surgeriesPage: "Surgeries",
    patientName: "Patient Name",
    surgeriesLabel: "Surgeries",
    edit: "Edit",
    surgeryData: "Surgery Date:",
    surgeryNotes: "Surgery Notes",
    addSurgery: "+ Add Surgery",
    editSurgery: "Edit Surgery",
    surgeryType: "Surgery Type",
    surgeryTypePlaceholder: "Type of surgery",
    surgeryDate: "Surgery Date",
    notes: "Notes",
    notesPlaceholder: "Enter any relevant notes",
    add: "Add",
  
    signIn: "Sign in",
    accessDoctor: "Access your clinical dashboard",
    accessPatient: "Access your health records",
    email: "Email or Username",
    emailPlaceholderDoctor: "doctor@ehrs.com or username",
    emailPlaceholderPatient: "patient@email.com or username",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember me",
    signInBtn: "Sign In",
    noAccount: "Don't have an account?",
    createAccount: "Create Account",
    signUp: "Create Account",
    createAccessDoctor: "Register as a healthcare provider",
    createAccessPatient: "Register for your health portal",
    fullName: "Full Name",
    namePlaceholder: "Enter your full name",
    confirmPassword: "Confirm Password",
    confirmPlaceholder: "Confirm your password",
    alreadyHaveAccount: "Already have an account?",
    signInLink: "Sign In",
    specialty: "Specialty",
    selectSpecialty: "Select a specialty",
    specialtyPlaceholder: "e.g. Cardiology, Pediatrics",
    licenseNumber: "Medical License Number",
    licensePlaceholder: "Enter your license number",
    gender: "Gender",
    genderPlaceholder: "Select gender",
    male: "Male",
    female: "Female",
    dateOfBirth: "Date of Birth",
    dobPlaceholder: "Select date of birth",
    nationalId: "National ID",
    nationalIdPlaceholder: "Enter your national ID",
    welcomeTo: "Welcome to",
    heroSubtitle: "Your trusted electronic health record system. Secure, intuitive, and designed for modern healthcare.",
    badge1: "HIPAA Compliant & Secure",
    badge2: "Trusted by 10,000+ providers",
    badge3: "99.99% Uptime SLA",
    // Validation
    validationError: "Validation Error",
    emailRequired: "Please enter your email or username.",
    emailInvalid: "Please enter a valid email or username.",
    emailAddress: "Email Address",
    emailAddressPlaceholder: "name@example.com",
    emailInvalidStrict: "Please enter a valid email address (e.g. name@example.com).",
    passwordRequired: "Please enter your password.",
    passwordIsEmail: "Password cannot be an email address.",
    passwordTooShort: "Password must be at least 8 characters.",
    nationalIdInvalid: "National ID must be exactly 14 digits (numbers only).",
    passwordsMismatch: "Passwords do not match.",
    fullNameRequired: "Please enter your full name.",
    fullNameInvalid: "Full name cannot contain numbers.",
    specialtyRequired: "Please select your specialty.",
    licenseRequired: "Please enter your medical license number.",
    genderRequired: "Please select your gender.",
    dobRequired: "Please select your date of birth.",
    nationalIdRequired: "Please enter your national ID.",
    successTitle: "Success",
    signInSuccess: "Signed in successfully.",
    accountCreated: "Account created successfully.",
    lockedTitle: "Too many attempts",
    lockedDesc: "Too many failed sign-in attempts. Please try again in",
    seconds: "seconds",
    invalidCredentials: "Invalid credentials. Please try again.",
    // Inline field errors
    nationalIdOnlyDigits: "Only numbers are allowed.",
    nationalIdLength: "National ID must be exactly 14 digits.",
    fullNameNoNumbers: "Name cannot contain numbers.",
    fullNameNoSymbols: "Name cannot contain special characters.",
    licenseOnlyAlnum: "Only letters and numbers are allowed.",
    passwordMinChars: "Must be at least 8 characters.",
    confirmMismatch: "Passwords do not match.",
    // Password complexity
    passwordNoLetters: "Password must contain at least one letter.",
    passwordNumericOnly: "Password cannot be numbers only — add at least one letter.",
    passwordWeak: "Password must be at least 8 characters and include letters and numbers.",
    // License validation
    licenseInvalidFormat: "License must be 5–20 alphanumeric characters (letters and numbers only).",
    licenseTooShort: "License number is too short (minimum 5 characters).",
    licenseTooLong: "License number is too long (maximum 20 characters).",
    // DOB picker
    dobConfirm: "Confirm",
    dobTooOld: "Date of birth cannot be more than 120 years ago.",
    dobFuture: "Date of birth cannot be in the future.",
    // Forgot password flow
    forgotTitle: "Forgot password",
    forgotStepEmailDesc: "Enter your account email and we'll send you a verification code.",
    forgotStepCodeDesc: "Enter the 6-digit code we sent to your email.",
    forgotStepResetDesc: "Choose a new password for your account.",
    sendCode: "Send code",
    verifyCode: "Verify code",
    resetPassword: "Reset password",
    saveNewPassword: "Save new password",
    backToSignIn: "Back to sign in",
    resendCode: "Resend code",
    resendIn: "Resend in",
    didntReceiveCode: "Didn't receive the code?",
    verificationCode: "Verification code",
    codePlaceholder: "000000",
    codeRequired: "Please enter the 6-digit code.",
    codeInvalid: "Code must be 6 digits.",
    codeSent: "Verification code sent to your email.",
    codeVerified: "Code verified successfully.",
    passwordChanged: "Password changed successfully. You can sign in now.",
    newPassword: "New password",
    newPasswordPlaceholder: "Enter new password",
    step: "Step",
    of: "of",

    // Common UI
    save: "Save",
    saveChanges: "Do you want to save changes?",
    delete: "Delete",
    logout: "Logout",
    yes: "Yes",
    no: "No",

    // Patient Dashboard
    patientDashboard: "Patient Dashboard",
    vitalSigns: "Vital Signs",
    temperature: "Temperature",
    heartRate: "Heart Rate",
    bloodPressure: "Blood Pressure",
    oxygenSat: "Oxygen Sat",
    upcomingAppointment: "Upcoming Appointment",
    todayAt: "Today, at 2:00 PM",
    drAhmed: "Dr. Ahmed",
    viewFullAppointment: "View Full Appointment",
    recentVisits: "Recent Visits",
    hypertension: "Hypertension",
    bloodPressureHigh: "Blood pressure high",
    diabetes: "Type 2 Diabetes",
    bloodSugarHigh: "Blood sugar high",
    flu: "Flu",
    feverCough: "Fever and cough",
    // Patient Appointments
    appointmentsTitle: "Appointments",
    labResults: "Lab Results Review",
    routineCheckup: "Routine Check-up",
    followUp: "Follow-up",
    today: "Today",
    // Booking
    bookingTitle: "Booking",
    bookNewAppointment: "Book a New Appointment",
    bookingSubtitle: "Select a doctor, pick a date and time to book a new appointment.",
    selectArea: "Select Area",
    selectDoctor: "Select Doctor",
    reasonForVisit: "Reason For Visit",
    bookAppointment: "Book Appointment",
    areas: ["Cairo", "Giza", "Alexandria", "Aswan", "Asyut", "Beheira", "Beni Suef", "Dakahlia", "Damietta", "Faiyum", "Sharqia", "Gharbia", "Ismailia", "Kafr El Sheikh", "Luxor", "Matruh", "Minya", "Monufia", "New Valley", "North Sinai", "Port Said", "Qalyubia", "Qena", "Red Sea", "Sohag", "South Sinai", "Suez"],
    specialties: ["General Practitioner (GP)", "Pediatrics Specialist", "Pediatric Surgery Specialist", "General Surgery Specialist", "Obstetrics and Gynecology Specialist", "Cardiology Specialist", "Neurology Specialist", "Vascular Specialist", "Chest Specialist (Pulmonology)", "Orthopedic Specialist", "Dermatology Specialist", "Internal Medicine Specialist", "Dentist", "ENT Specialist", "Urology Specialist", "Ophthalmology Specialist", "Rheumatology Specialist"],
    visitReasons: ["Follow-up", "Routine Check-up", "Consultation", "Lab Results Review"],
    // Medical History
    medicalHistoryTitle: "Medical History",
    allergies: "Allergies",
    surgeries: "Surgeries",
    selectDisease: "Select Disease",
    selectAllergy: "Select Allergy",
    selectSurgery: "Select Surgery",
    diseasesList: ["Diabetes", "Hypertension", "Heart Disease", "Asthma", "Cancer", "Depression", "Coronary Artery Disease", "Heart Failure", "Chronic Obstructive Pulmonary Disease", "Chronic Kidney Disease", "Chronic Liver Disease", "Liver Cirrhosis", "Epilepsy", "Thyroid Disorder", "Hyperthyroidism", "Hypothyroidism", "Hyperlipidemia", "Rheumatoid Arthritis", "Osteoporosis", "Anxiety Disorder", "Systemic Lupus Erythematosus", "Chronic Anemia", "Parkinson's Disease", "Alzheimer's Disease", "Other"],
    allergiesList: ["Penicillin", "Aspirin", "Dust", "Milk", "Peanuts", "Perfume", "Antibiotics Allergy", "Ibuprofen Allergy", "Sulfa Drugs Allergy", "Tree Nuts Allergy", "Egg Allergy", "Fish Allergy", "Shellfish Allergy", "Wheat Allergy", "Soy Allergy", "Pollen Allergy", "Pet Dander Allergy", "Mold Allergy", "Latex Allergy", "Insect Sting Allergy", "Sun Allergy", "Other"],
    surgeriesList: ["Appendectomy", "Cholecystectomy", "Coronary Artery Bypass", "Hip Replacement", "Knee Replacement", "Spinal Fusion", "Cataract Surgery", "Thyroidectomy", "Hysterectomy", "Cesarean Section", "Tonsillectomy", "Hernia Repair", "Colostomy", "Mastectomy", "Prostatectomy", "Other"],
    // Personal Information
    personalInfoTitle: "Personal Information",
    changePhoto: "Change Photo",
    fieldLabels: {
      patientId: "Patient ID",
      fullName: "Full Name",
      gender: "Gender",
      birthDate: "Birth Date",
      email: "Email",
      phone: "Phone",
      address: "Address",
      bloodType: "Blood Type",
      height: "Height",
      weight: "Weight",
      ssn: "National ID Number",
      contactNumber: "Phone Number",
      heightCm: "Height (cm)",
      weightKg: "Weight (kg)",
      age: "Age"
    },
    // Prescriptions
    prescriptionsTitle: "Prescriptions",
    active: "Active",
    uploadPdf: "Upload PDF",
    download: "Download",
    dermatologist: "Dermatologist",
    // Imaging
    imagingTitle: "Imaging & Radiology",
    search: "Search",
  },
  ar: {
    // Sidebar
    healthcarePortal: "بوابة الرعاية الصحية",
    mainMenu: "القائمة الرئيسية",
    dashboard: "لوحة التحكم",
    appointments: "المواعيد",
    medicalRecords: "السجلات",
    doctorProfile: "الملف الشخصي",
    searchPatientNav: "بحث",
    surgeriesNav: "العمليات",

    // Header
    language: "العربية",
    searchPatients: "بحث عن مريض…",

    // Dashboard
    drName: "د. جون دو",
    noRecentVisits: "لا توجد زيارات مسجلة.",
    noAppointmentsFound: "لا توجد مواعيد.",
    noImagingFound: "لا توجد سجلات تصوير.",
    bookingSelectAreaFirst: "يرجى اختيار المحافظة أولاً.",
    bookingSelectSpecialtyFirst: "يرجى اختيار التخصص أولاً.",
    bookingFillAllFields: "يرجى ملء جميع الحقول المطلوبة.",
    bookingSuccess: "تم حجز الموعد بنجاح!",
    bookingDuplicate: "لديك موعد محجوز في هذا التاريخ بالفعل.",
    bookingPastDate: "يرجى اختيار تاريخ اليوم أو تاريخ مستقبلي.",
    bookingAvailableDoctors: "الأطباء المتاحون",
    bookingNoSlots: "لا يوجد أطباء متاحون لهذا الاختيار.",
    selectGovernorate: "اختر المحافظة",
    phoneInvalid: "رقم الهاتف يجب أن يكون 11 رقمًا.",
    dobInvalid: "يرجى إدخال تاريخ ميلاد صحيح.",
    imageTypeError: "يُسمح فقط بصور JPEG و PNG و WebP.",
    selectBloodType: "اختر فصيلة الدم",
    cardiologist: "طبيب قلب",
    todaysAppointments: "مواعيد اليوم",
    patient: "المريض",
    status: "الحالة",

    // Appointments
    manageAppointments: "إدارة وعرض جميع مواعيد المرضى",
    upcoming: "القادمة",
    past: "السابقة",
    upcomingAppointments: "المواعيد القادمة",
    pastAppointments: "المواعيد السابقة",
    searchPatient: "بحث عن مريض...",
    date: "التاريخ",
    type: "النوع",
    id: "المعرف",

    // Statuses
    waiting: "في الانتظار",
    completed: "مكتمل",
    cancelled: "ملغي",
    scheduled: "مجدول",

    // Medical Records
    generalDocuments: "المستندات العامة / السجلات الطبية",
    patientRecords: "سجلات المرضى",
    searchPatientRecord: "بحث عن مريض…",
    diagnosis: "التشخيص",
    treatment: "العلاج",
    action: "إجراء",
    view: "عرض",
    addRecord: "إضافة سجل",

    // New Medical Record
    newMedicalRecord: "سجل طبي جديد",
    fillDetails: "املأ التفاصيل لإنشاء سجل طبي جديد",
    backToMedicalRecords: "العودة للسجلات الطبية",
    referenceIds: "المعرفات المرجعية",
    patientId: "معرف المريض",
    doctorId: "معرف الطبيب",
    appointmentId: "معرف الموعد",
    searchPatientId: "بحث عن معرف المريض…",
    searchDoctorId: "بحث عن معرف الطبيب…",
    searchAppointmentId: "بحث عن معرف الموعد…",
    medicalInformation: "المعلومات الطبية",
    chiefComplaint: "الشكوى الرئيسية",
    clinicalNotes: "الملاحظات السريرية",
    describeComplaint: "وصف الشكوى الرئيسية للمريض…",
    enterDiagnosis: "أدخل التشخيص…",
    addClinicalNotes: "أضف الملاحظات والملاحظات السريرية…",
    describeTreatment: "وصف خطة العلاج…",
    attachments: "المرفقات",
    prescription: "الوصفة الطبية",
    radiology: "الأشعة",
    noFileChosen: "لم يتم اختيار ملف",
    chooseFile: "اختر ملف",
    cancel: "إلغاء",

    // Doctor Profile
    editProfile: "تعديل الملف",
    saveProfile: "حفظ الملف",
    medicalLicense: "الترخيص الطبي",
    contact: "التواصل",
    affiliatedHospital: "المستشفى التابع",
    about: "نبذة",
    cardiology: "أمراض القلب",

    // Not Found
    notFound: "404",
    pageNotFound: "عذراً! الصفحة غير موجودة",
    returnHome: "العودة للرئيسية",

    // Search Patient Page
    searchPatientPage: "بحث عن مريض",
    medicalHistoryTab: "التاريخ الطبي",
    surgeryTab: "الجراحة",
    enterPatientId: "أدخل الرقم القومي",
    searchBtn: "بحث",
    patientNotFound: "المريض غير موجود. يرجى التحقق من المعرف.",
    idTooShort: "الرقم القومي يجب أن يكون 14 رقماً بالضبط. أدخلت أرقاماً أقل.",
    idTooLong: "الرقم القومي يجب أن يكون 14 رقماً بالضبط. أدخلت أرقاماً أكثر.",
    idInvalid: "الرقم القومي يجب أن يحتوي على أرقام فقط.",
    bloodType: "فصيلة الدم",
    age: "العمر",
    weight: "الوزن",
    height: "الطول",
    bmi: "مؤشر كتلة الجسم",
    years: "سنة",
    kg: "كجم",
    cm: "سم",
    chronicDiseases: "الأمراض المزمنة",
    allergiesLabel: "الحساسية",
    doctor: "الطبيب",
    surgicalHistory: "التاريخ الجراحي",
    operationName: "اسم العملية",

    // Surgeries Page
    surgeriesPage: "العمليات الجراحية",
    patientName: "اسم المريض",
    surgeriesLabel: "العمليات",
    edit: "تعديل",
    surgeryData: "تاريخ العملية:",
    surgeryNotes: "ملاحظات العملية",
    addSurgery: "+ إضافة عملية",
    editSurgery: "تعديل العملية",
    surgeryType: "نوع العملية",
    surgeryTypePlaceholder: "نوع العملية الجراحية",
    surgeryDate: "تاريخ العملية",
    notes: "ملاحظات",
    notesPlaceholder: "أدخل أي ملاحظات ذات صلة",
    add: "إضافة",
  
    signIn: "تسجيل الدخول",
    accessDoctor: "الوصول إلى لوحة التحكم السريرية",
    accessPatient: "الوصول إلى سجلاتك الصحية",
    email: "البريد الإلكتروني أو اسم المستخدم",
    emailPlaceholderDoctor: "doctor@ehrs.com أو اسم المستخدم",
    emailPlaceholderPatient: "patient@email.com أو اسم المستخدم",
    password: "كلمة المرور",
    passwordPlaceholder: "أدخل كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    rememberMe: "تذكرني",
    signInBtn: "تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    createAccount: "إنشاء حساب",
    signUp: "إنشاء حساب",
    createAccessDoctor: "التسجيل كمقدم رعاية صحية",
    createAccessPatient: "التسجيل في بوابتك الصحية",
    fullName: "الاسم الكامل",
    namePlaceholder: "أدخل اسمك الكامل",
    confirmPassword: "تأكيد كلمة المرور",
    confirmPlaceholder: "أكد كلمة المرور",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    signInLink: "تسجيل الدخول",
    specialty: "التخصص",
    selectSpecialty: "اختر التخصص",
    specialtyPlaceholder: "مثال: أمراض القلب، طب الأطفال",
    licenseNumber: "رقم الترخيص الطبي",
    licensePlaceholder: "أدخل رقم الترخيص",
    gender: "النوع",
    genderPlaceholder: "اختر النوع",
    male: "ذكر",
    female: "أنثى",
    dateOfBirth: "تاريخ الميلاد",
    dobPlaceholder: "اختر تاريخ الميلاد",
    nationalId: "الرقم القومي",
    nationalIdPlaceholder: "أدخل الرقم القومي",
    welcomeTo: "مرحبًا بك في",
    heroSubtitle: "نظام السجلات الصحية الإلكترونية الموثوق. آمن وبديهي ومصمم للرعاية الصحية الحديثة.",
    badge1: "متوافق مع HIPAA وآمن",
    badge2: "موثوق من 10,000+ مقدم خدمة",
    badge3: "99.99% وقت تشغيل مضمون",
    // Validation
    validationError: "خطأ في التحقق",
    emailRequired: "يرجى إدخال بريدك الإلكتروني أو اسم المستخدم.",
    emailInvalid: "يرجى إدخال بريد إلكتروني أو اسم مستخدم صحيح.",
    emailAddress: "البريد الإلكتروني",
    emailAddressPlaceholder: "name@example.com",
    emailInvalidStrict: "يرجى إدخال بريد إلكتروني صحيح (مثال: name@example.com).",
    passwordRequired: "يرجى إدخال كلمة المرور.",
    passwordIsEmail: "كلمة المرور لا يمكن أن تكون بريدًا إلكترونيًا.",
    passwordTooShort: "كلمة المرور يجب أن تكون 8 أحرف على الأقل.",
    nationalIdInvalid: "الرقم القومي يجب أن يكون 14 رقمًا بالضبط (أرقام فقط).",
    passwordsMismatch: "كلمتا المرور غير متطابقتين.",
    fullNameRequired: "يرجى إدخال اسمك الكامل.",
    fullNameInvalid: "الاسم الكامل لا يمكن أن يحتوي على أرقام.",
    specialtyRequired: "يرجى اختيار تخصصك.",
    licenseRequired: "يرجى إدخال رقم الترخيص الطبي.",
    genderRequired: "يرجى اختيار النوع.",
    dobRequired: "يرجى اختيار تاريخ الميلاد.",
    nationalIdRequired: "يرجى إدخال الرقم القومي.",
    successTitle: "تم بنجاح",
    signInSuccess: "تم تسجيل الدخول بنجاح.",
    accountCreated: "تم إنشاء الحساب بنجاح.",
    lockedTitle: "محاولات كثيرة جدًا",
    lockedDesc: "تم تجاوز عدد محاولات تسجيل الدخول. يرجى المحاولة مرة أخرى بعد",
    seconds: "ثانية",
    invalidCredentials: "بيانات الدخول غير صحيحة. حاول مرة أخرى.",
    // Inline field errors
    nationalIdOnlyDigits: "يُسمح بالأرقام فقط.",
    nationalIdLength: "الرقم القومي يجب أن يكون 14 رقمًا بالضبط.",
    fullNameNoNumbers: "الاسم لا يمكن أن يحتوي على أرقام.",
    fullNameNoSymbols: "الاسم لا يمكن أن يحتوي على رموز خاصة.",
    licenseOnlyAlnum: "يُسمح بالحروف والأرقام فقط.",
    passwordMinChars: "يجب أن تكون 8 أحرف على الأقل.",
    confirmMismatch: "كلمتا المرور غير متطابقتين.",
    // Password complexity
    passwordNoLetters: "يجب أن تحتوي كلمة المرور على حرف واحد على الأقل.",
    passwordNumericOnly: "كلمة المرور لا يمكن أن تكون أرقامًا فقط — أضف حرفًا واحدًا على الأقل.",
    passwordWeak: "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتتضمن حروفًا وأرقامًا.",
    // License validation
    licenseInvalidFormat: "يجب أن يكون رقم الترخيص من 5 إلى 20 حرفًا أبجديًا رقميًا.",
    licenseTooShort: "رقم الترخيص قصير جدًا (الحد الأدنى 5 أحرف).",
    licenseTooLong: "رقم الترخيص طويل جدًا (الحد الأقصى 20 حرفًا).",
    // DOB picker
    dobConfirm: "تأكيد",
    dobTooOld: "لا يمكن أن يكون تاريخ الميلاد قبل أكثر من 120 سنة.",
    dobFuture: "لا يمكن أن يكون تاريخ الميلاد في المستقبل.",
    // Forgot password flow
    forgotTitle: "نسيت كلمة المرور",
    forgotStepEmailDesc: "أدخل البريد الإلكتروني المسجل وسنرسل إليك رمز تحقق.",
    forgotStepCodeDesc: "أدخل رمز التحقق المكوّن من 6 أرقام المُرسل إلى بريدك.",
    forgotStepResetDesc: "اختر كلمة مرور جديدة لحسابك.",
    sendCode: "إرسال الرمز",
    verifyCode: "تحقق من الرمز",
    resetPassword: "إعادة تعيين كلمة المرور",
    saveNewPassword: "حفظ كلمة المرور الجديدة",
    backToSignIn: "العودة لتسجيل الدخول",
    resendCode: "إعادة إرسال الرمز",
    resendIn: "إعادة الإرسال خلال",
    didntReceiveCode: "لم يصلك الرمز؟",
    verificationCode: "رمز التحقق",
    codePlaceholder: "000000",
    codeRequired: "يرجى إدخال الرمز المكوّن من 6 أرقام.",
    codeInvalid: "الرمز يجب أن يتكون من 6 أرقام.",
    codeSent: "تم إرسال رمز التحقق إلى بريدك.",
    codeVerified: "تم التحقق من الرمز بنجاح.",
    passwordChanged: "تم تغيير كلمة المرور بنجاح. يمكنك تسجيل الدخول الآن.",
    newPassword: "كلمة المرور الجديدة",
    newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
    step: "الخطوة",
    of: "من",

    // Common UI
    save: "حفظ",
    saveChanges: "هل تريد حفظ التغييرات؟",
    delete: "حذف",
    logout: "تسجيل الخروج",
    yes: "نعم",
    no: "لا",

    // Patient Dashboard
    patientDashboard: "لوحة تحكم المريض",
    vitalSigns: "العلامات الحيوية",
    temperature: "درجة الحرارة",
    heartRate: "معدل ضربات القلب",
    bloodPressure: "ضغط الدم",
    oxygenSat: "نسبة الأكسجين",
    upcomingAppointment: "الموعد القادم",
    todayAt: "اليوم، الساعة 2:00 مساءً",
    drAhmed: "د. أحمد",
    viewFullAppointment: "عرض الموعد كاملاً",
    recentVisits: "الزيارات الأخيرة",
    hypertension: "ارتفاع ضغط الدم",
    bloodPressureHigh: "ضغط الدم مرتفع",
    diabetes: "السكري من النوع الثاني",
    bloodSugarHigh: "نسبة السكر في الدم مرتفعة",
    flu: "الإنفلونزا",
    feverCough: "حمى وسعال",
    // Patient Appointments
    appointmentsTitle: "المواعيد",
    labResults: "مراجعة نتائج المختبر",
    routineCheckup: "فحص روتيني",
    followUp: "متابعة",
    today: "اليوم",
    // Booking
    bookingTitle: "الحجز",
    bookNewAppointment: "حجز موعد جديد",
    bookingSubtitle: "اختر طبيباً وحدد تاريخاً ووقتاً لحجز موعد جديد.",
    selectArea: "اختر المنطقة",
    selectDoctor: "اختر الطبيب",
    reasonForVisit: "سبب الزيارة",
    bookAppointment: "احجز الموعد",
    areas: ["القاهرة", "الجيزة", "الإسكندرية", "أسوان", "أسيوط", "البحيرة", "بني سويف", "الدقهلية", "دمياط", "الفيوم", "الشرقية", "الغربية", "الإسماعيلية", "كفر الشيخ", "الأقصر", "مطروح", "المنيا", "المنوفية", "الوادي الجديد", "شمال سيناء", "بورسعيد", "القليوبية", "قنا", "البحر الأحمر", "سوهاج", "جنوب سيناء", "السويس"],
    specialties: ["طبيب عام", "أخصائي أطفال", "أخصائي جراحة أطفال", "أخصائي جراحة عامة", "أخصائي نساء وتوليد", "أخصائي قلب", "أخصائي مخ وأعصاب", "أخصائي أوعية دموية", "أخصائي صدر", "أخصائي عظام", "أخصائي جلدية", "أخصائي باطنة", "طبيب أسنان", "أخصائي أنف وأذن وحنجرة", "أخصائي مسالك بولية", "أخصائي عيون", "أخصائي روماتيزم"],
    visitReasons: ["متابعة", "فحص روتيني", "استشارة", "مراجعة نتائج المختبر"],
    // Medical History
    medicalHistoryTitle: "السجل الطبي",
    allergies: "الحساسية",
    surgeries: "العمليات الجراحية",
    selectDisease: "اختر المرض",
    selectAllergy: "اختر الحساسية",
    selectSurgery: "اختر العملية",
    diseasesList: ["السكري", "ارتفاع ضغط الدم", "أمراض القلب", "الربو", "السرطان", "الاكتئاب", "مرض الشرايين التاجية", "فشل القلب", "الانسداد الرئوي المزمن", "أمراض الكلى المزمنة", "أمراض الكبد المزمنة", "تليف الكبد", "الصرع", "اضطرابات الغدة الدرقية", "فرط نشاط الغدة الدرقية", "قصور الغدة الدرقية", "ارتفاع الكوليسترول", "التهاب المفاصل الروماتويدي", "هشاشة العظام", "اضطراب القلق", "الذئبة الحمراء", "فقر الدم المزمن", "مرض باركنسون", "مرض الزهايمر", "أخرى"],
    allergiesList: ["البنسلين", "الأسبرين", "الغبار", "الحليب", "الفول السوداني", "العطور", "حساسية المضادات الحيوية", "حساسية الإيبوبروفين", "حساسية أدوية السلفا", "حساسية المكسرات الشجرية", "حساسية البيض", "حساسية السمك", "حساسية المحار", "حساسية القمح", "حساسية الصويا", "حساسية حبوب اللقاح", "حساسية وبر الحيوانات", "حساسية العفن", "حساسية اللاتكس", "حساسية لسعات الحشرات", "حساسية الشمس", "أخرى"],
    surgeriesList: ["استئصال الزائدة الدودية", "استئصال المرارة", "تحويل مسار الشريان التاجي", "استبدال مفصل الورك", "استبدال مفصل الركبة", "اندماج العمود الفقري", "جراحة الساد", "استئصال الغدة الدرقية", "استئصال الرحم", "الولادة القيصرية", "استئصال اللوزتين", "إصلاح الفتق", "فغر القولون", "استئصال الثدي", "استئصال البروستاتا", "أخرى"],
    // Personal Information
    personalInfoTitle: "المعلومات الشخصية",
    changePhoto: "تغيير الصورة",
    fieldLabels: {
      patientId: "رقم المريض",
      fullName: "الاسم الكامل",
      gender: "الجنس",
      birthDate: "تاريخ الميلاد",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      address: "العنوان",
      bloodType: "فصيلة الدم",
      height: "الطول",
      weight: "الوزن",
      ssn: "الرقم القومي",
      contactNumber: "رقم الهاتف",
      heightCm: "الطول (سم)",
      weightKg: "الوزن (كجم)",
      age: "العمر"
    },
    // Prescriptions
    prescriptionsTitle: "الوصفات الطبية",
    active: "نشطة",
    uploadPdf: "رفع ملف PDF",
    download: "تنزيل",
    dermatologist: "أخصائي جلدية",
    // Imaging
    imagingTitle: "التصوير والأشعة",
    search: "بحث",
  }
};


export const SPECIALTIES: { key: string; en: string; ar: string }[] = [
  { key: "general_practitioner_gp", en: "General Practitioner (GP)", ar: "طبيب عام (GP)" },
  { key: "pediatrics_specialist", en: "Pediatrics Specialist", ar: "أخصائي طب الأطفال" },
  { key: "pediatric_surgery_specialist", en: "Pediatric Surgery Specialist", ar: "أخصائي جراحة الأطفال" },
  { key: "general_surgery_specialist", en: "General Surgery Specialist", ar: "أخصائي الجراحة العامة" },
  { key: "obstetrics_gynecology_specialist", en: "Obstetrics and Gynecology Specialist", ar: "أخصائي نساء وتوليد" },
  { key: "cardiology_specialist", en: "Cardiology Specialist", ar: "أخصائي قلب" },
  { key: "neurology_specialist", en: "Neurology Specialist", ar: "أخصائي أعصاب" },
  { key: "vascular_specialist", en: "Vascular Specialist", ar: "أخصائي الأوعية الدموية" },
  { key: "chest_specialist_pulmonology", en: "Chest Specialist (Pulmonology)", ar: "أخصائي صدر (جهاز تنفسي)" },
  { key: "orthopedic_specialist", en: "Orthopedic Specialist", ar: "أخصائي عظام" },
  { key: "dermatology_specialist", en: "Dermatology Specialist", ar: "أخصائي جلدية" },
  { key: "internal_medicine_specialist", en: "Internal Medicine Specialist", ar: "أخصائي الباطنة" },
  { key: "dentist", en: "Dentist", ar: "طبيب أسنان" },
  { key: "ent_specialist", en: "ENT Specialist", ar: "أخصائي أنف وأذن وحنجرة" },
  { key: "urology_specialist", en: "Urology Specialist", ar: "أخصائي مسالك بولية" },
  { key: "ophthalmology_specialist", en: "Ophthalmology Specialist", ar: "أخصائي عيون" },
  { key: "rheumatology_specialist", en: "Rheumatology Specialist", ar: "أخصائي الروماتيزم" },
];

type Translations = typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  t: Translations;
  toggleLang: () => void;
  setLang: (l: Lang) => void;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  t: translations.en,
  toggleLang: () => {},
  setLang: () => {},
  isRtl: false,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const toggleLang = () => {
    setLang((prev) => (prev === "en" ? "ar" : "en"));
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const isRtl = lang === "ar";
  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang, setLang, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
